---
fluxbb_domain: bbs.archlinux.org
fluxbb_dir: /srv/http/fluxbb

fluxbb_cookie_name: flux_cookie_eezohm0o
fluxbb_funnyquestion_hash: aixuGahCh4eng3bu
fluxbb_version: 411f2f32ff005fde24fd9896c88bb1ad2d9c9eb8
