---
fluxbb_domain: bbs.archlinux.org
fluxbb_dir: /srv/http/fluxbb

fluxbb_cookie_name: flux_cookie_eezohm0o
fluxbb_cookie_seed: huathe3ooZuwieba
fluxbb_funnyquestion_hash: aixuGahCh4eng3bu

php_extensions:
  - iconv
  - intl
  - mysqli
  - apcu
