$ANSIBLE_VAULT;1.1;AES256
64366238333061393032396539623632323166653730666662623134613230616161336135613433
3739323031636132393562316630393762636561336537630a666131626539656362366437316130
33656264643436333532386230303634393437326463313336363534643364626162326132623565
3838333866343535610a333738333364666434323235633064633537656231393637636365663030
39366236393563373038383362623563363862343033656231323863393961633734663736313637
37313963303235613065636337393533656639663738383664633033326231393331613564656436
35323033323234316261353931343635653235336439653133636566356166373961626263333764
33393433653438643330303063363061653065386439663035343466383164383063313666303265
65323230363730656533356131353762373563663338623964646165393736316661
