$ANSIBLE_VAULT;1.1;AES256
30333461333766363765626134636566653530653938393334396461346639613134396539623665
3063396532666366353734636232303835353030383037300a323464316334663430333537306439
34323665386361303033316430663238313965626434393963343265306536333830393330366630
3239336130323032650a366665643237313463366465653038313863646538383036623636383636
64663534363930633461306666623236383633333366613561386665623931396361333630363765
34653363626236343136396434376539653339633937373961323938356535363337323466376565
35643161333965613166376238336230323134373262373233383165343630343530653263626365
61313662323766346237356161323232666561333638653065353534303339376565623831666366
35666661373164313031626435346465313866613664336166636131616631663135643366336233
30353738323264663435343738346264613765653436663966383066326534626631656438663334
38666461663434626632356661386536653039326135616463326237613936366334383039613637
61366433623336323463333932306264373264363932376337383261666539313631636563393463
3039
