---
patchwork_dir: '/srv/http/patchwork'
patchwork_domain: 'patchwork.archlinux.org'
patchwork_nginx_conf: '/etc/nginx/nginx.d/patchwork.conf'
patchwork_forced_deploy: false
patchwork_admins: ["('Giancarlo Razzolini', 'grazzolini@archlinux.org')"]
patchwork_version: 'v2.1.5'
patchwork_from_email: 'Arch Linux Patchwork <patchwork@patchwork.archlinux.org>'
patchwork_notification_frequency: '10m'

patchwork_db: 'patchwork'
patchwork_db_host: 'localhost'
patchwork_db_user: 'patchwork'
patchwork_db_backup_user: 'patchwork_backup'
patchwork_db_backup_table_objs: 'ALL_IN_SCHEMA'
patchwork_db_backup_sequence_objs: 'ALL_IN_SCHEMA'
