$ANSIBLE_VAULT;1.1;AES256
37303330663762383063386562396436306531636663333038353937663436656439343934663931
3764626438363664663166313037346433376465666365390a343130643263343964656332323237
38313965616632316334643233316564393636623162633031383332653961386561663832656235
6564643038633466630a663262666632353461363830643664303138356633653061616164366565
38643064353135643265643137356364653461333637303431303131373637616162653937366164
65353132313231346230613962303233656562303063323633613461343832353233316135346534
31373362313765316533366133393864326235613937656431306134316135643433376562623030
62356266666365323934363337633433353565653438303163633535346134323164363531333165
34333531363831343038663237323063343933376136363366336433336265323730663165666466
30306162393162356162613936613265373263656630363463643231333932376365353166323665
63363336643362323964313432613863333239343239663137396337623139336233393265313062
38373332376463363566313039336465346534363636356338646438303634353330653963303830
33313161336236333833633836323039656566353965653635323731616233666462616337333137
63643464333330396539323334393165383563393039653063386231623439333661313833643334
643563323063316162346536613033663731
