$ANSIBLE_VAULT;1.1;AES256
63303532643562376339303165643765613763623164633539306466383364343036336337393334
6135636665643731393934363963343032663239313965390a656566303564386234393965346636
61306438643935306531626438626138336638623239643962336638373632653838636661373462
3166396139323937640a366232313039323734366166363935396433313935616437356432656132
35646538613266353232333937373666373261353338386632636237666438393465343130333738
65663265623837393637613861636261336636653538336361343861643866633333363039653336
31643638643562303238393933613362353764326630313230353634366561306233316334613661
64353538643536666663363166656566323464393334303530363863316462373033623661346235
31353734323363383039396432653238313262656538616366316630353639646530616332393737
63336666313437386132623839303238396264376336316362393666633865626363613064323933
66326538343030346461396233336536663334646231643639663736613937336436313835666362
33386437613132323930306433393036333466366439373537646136396337396632626632303665
39323164393733643366346133623834663334643364616338633935373065633033346330396539
35633562303632643030666466613334663139333335666266653137663938373134386461303434
61666462363239386162313861316336353531396664623239383738613034303461613637633432
37373265373666343839
