$ANSIBLE_VAULT;1.1;AES256
34363062613532343565326535633130663465363434376635323838633261303930336134333936
3961323164393738623337373533383736646136353662340a336662303265643365623439633237
35396331303461353331323636393338336337363861383162366630326436666235373833343661
6237363264623735300a333562363233616365616535353332663238373761376333643631326565
30623963623766323262643434396339323066306237613131343436393564353832373864313832
32326536343539363630316366363964613566383564653132343732396666666363363166613261
33333534366433363435363037373239316563633139323138306431633961393661303661663761
35646631643835346163336635663632373339343530396530343733613539636232323438323830
65343462313662303462363532306431313066383163633163343033363266626239643833636632
64633566313635323836316633653234323730366562396266326434616538313438356465343633
65646333396338323939653332363764373737316162396437636565393463373866653438653061
36393365626265383362303862616134656636303764326261626132643932306339353331336439
6264
