$ANSIBLE_VAULT;1.1;AES256
36356232653334343137636165613839633465363335393734623864343738373136326332613734
3462313335656338366530643634623936633237303262300a393738653733653433613737646134
63613838653466663235326431636532663035313737663737646533393761373836646531616161
3832333162656435610a656133666630366332386132613865353330653765623735313162333535
64323765623166356266316666353364346434353661643731643362613733323463343532336433
34376237613139616237383861366661356565643665303232353039373135633466343037656232
34623132313733393335323164653735326436626634376332353232303932373130656261303338
39613666303837306364373935343338383130373137386265623762373733343065396134313631
31653165316632663633663637303065626438396166396664303537636161663965396561323465
35666435643366373630393238643666653732386666313438613662366465363965363639653166
35333434343538363839383065333134373863386463393839663034393264666462326438656436
37326566646633376439
