$ANSIBLE_VAULT;1.1;AES256
37343133346535636364636138393765376534366636376139353339333262353632393232316235
3964363934373962646664346437346661643364656434320a633366323935373565333831616231
30613234303430666135613637313231353161333938376165376431353463363939373936613837
3837613639633962380a336262303833656139303034393434366334396236633366376464323065
65643332356634623065643731633063343330313331356362363832343331646232343566643937
37393831313562653862613930613362356436383962343135633332613539326462356565316439
36343138363466303062663263323866303266313139323639363939303531336634313837613366
31626132323034306439323061643231613462356239306134646338643864353866353933656465
32366439346435613534363665663865343964363034643039373834363630343133376337376566
35386430383961383633346662613762303135303234323961346436323338376631626661646264
38643563323836336538343938623061333937626130643466616532613236636264346234613761
61376631343934626662336438373737633935363363336434383233373464633230626564663533
66376466623433316632323331316134343962653938636635653236303536373233
