gitlab_bots:
  - renovate
  - bugbuddy
  - project_10185_bot2
  - project_19591_bot
  - project_19796_bot
  - project_10185_bot_6f3a8a11922b9008fcb92024361b10b6
  - project_19709_bot_ab88a35474b62399f347877ec82018ac
  - project_16_bot_32e6f4728202b8f9259313830e9e5a18
  - project_32147_bot_17ab98ea29bb8d2f93c685af009e3376
  - project_84858_bot_e982c0734ca839275298899e49ed1f51
  - project_10177_bot_5b2d333786a259642a61351696877bae
  - project_10177_bot_a8dd89a4bf249d4b5d3ec1c3d46e8caf
  - bumpbuddy
  - project_57074_bot_f7e3b3fe2a01bef8e3aa5ed9d34b741b
  # group/packaging-buildbtw-dev, user: buildbtw-dev test
  - group_81209_bot_10e437f10042ac36030406d8523b7954
  # archlinux/devblog, gitlab issue bot
  - project_98291_bot_6369e6b37b8d1e0ecabbbb4dabfb5c21
  # archlinux/archlinux-wsl, token for cleaning up the package registry
  - project_85684_bot_601164180ca9019d6ade06b04b0161da
  # archlinux/archlinux-wsl, gitlab issue bot
  - project_85684_bot_1c840b3a28d3a03d2a13ef0b9aea2ed9
  # archlinux/alpm/voa, gitlab issue bot
  - project_99023_bot_7da23d67ceaee3a657df421e78ee0fc9
  - gluebuddy
  # gitlab security bots, added in here until we have an implementation for
  # https://gitlab.archlinux.org/archlinux/gluebuddy/-/issues/21
  - gitlab_security_policy_project_10263_bot_5f978e46a682934b2d98646d173ce477
  - gitlab_security_policy_project_11_bot_beaed130992c427ca86c75e17ac4be85
  - gitlab_security_policy_project_13_bot_b6b83ffdea6eddec737fb32d5fba61e7
  - gitlab_security_policy_project_16_bot_99b50844cc6cd6c5a180da35db9bfdf1
  - gitlab_security_policy_project_19588_bot_748916d1584e7816a9a662e804655fd6
  - gitlab_security_policy_project_19_bot_f41b9343c6743b685288ec61580d7a4e
  - gitlab_security_policy_project_7_bot_7e72a89174cbe78e97d551e6f92c5d9
  - gitlab_security_policy_project_7_bot_7e72a89174cbe78e97d551e6f92c5d91
  - gitlab_security_policy_project_84181_bot_93055301c2b0187ebadced47192ea608
  - gitlab_security_policy_project_84422_bot_22144c24fc29c9ed7f8617a2cd8eadac
  - gitlab_security_policy_project_84858_bot_d78be3051ac27beb42d82fd43691073a
  - gitlab_security_policy_project_99023_bot_54ef85afd5fe6d9832139e79901c666c
  # archlinux/account-allowlist, allowlist bot
  - project_100502_bot_e72660623d782cd4a8667b213bcc00af
  # archlinux/account-allowlist, gitlab issue bot
  - project_100502_bot_e12ccfdac7cc5cf30c084276a2ad1cdd
