gitlab_bots:
  - renovate
  - bugbuddy
  - project_10185_bot2
  - project_19591_bot
  - project_19796_bot
  - project_10185_bot_6f3a8a11922b9008fcb92024361b10b6
  - project_19709_bot_ab88a35474b62399f347877ec82018ac
  - project_16_bot_32e6f4728202b8f9259313830e9e5a18
  - project_32147_bot_17ab98ea29bb8d2f93c685af009e3376
  - project_84858_bot_e982c0734ca839275298899e49ed1f51
  - project_10177_bot_5b2d333786a259642a61351696877bae
  - project_10177_bot_a8dd89a4bf249d4b5d3ec1c3d46e8caf
  - bumpbuddy
  - project_57074_bot_f7e3b3fe2a01bef8e3aa5ed9d34b741b
  # group/packaging-buildbtw-dev, user: buildbtw-dev test
  - group_81209_bot_10e437f10042ac36030406d8523b7954
  # archlinux/devblog, gitlab issue bot
  - project_98291_bot_6369e6b37b8d1e0ecabbbb4dabfb5c21
  # archlinux/archlinux-wsl, token for cleaning up the package registry
  - project_85684_bot_601164180ca9019d6ade06b04b0161da
  # archlinux/archlinux-wsl, gitlab issue bot
  - project_85684_bot_1c840b3a28d3a03d2a13ef0b9aea2ed9
  # archlinux/alpm/voa, gitlab issue bot
  - project_99023_bot_7da23d67ceaee3a657df421e78ee0fc9
  - gluebuddy
  # gitlab security bots, added in here until we have an implementation for
  # https://gitlab.archlinux.org/archlinux/gluebuddy/-/issues/21
  - gitlab_security_policy_project_100299_bot_a9b6b899acd32d66e7f18af52901bcbb
  - gitlab_security_policy_project_100301_bot_4b1886e6d20f2e497f1dfb8b0c809acb
  - gitlab_security_policy_project_10263_bot_5f978e46a682934b2d98646d173ce477
  - gitlab_security_policy_project_11_bot_beaed130992c427ca86c75e17ac4be85
  - gitlab_security_policy_project_13_bot_b6b83ffdea6eddec737fb32d5fba61e7
  - gitlab_security_policy_project_16_bot_99b50844cc6cd6c5a180da35db9bfdf1
  - gitlab_security_policy_project_19588_bot_748916d1584e7816a9a662e804655fd6
  - gitlab_security_policy_project_19777_bot_9fcc6c1f509d956e3db85659f1351f76
  - gitlab_security_policy_project_19_bot_f41b9343c6743b685288ec61580d7a4e
  - gitlab_security_policy_project_20028_bot_3e0d5e9664d71769f32ba3f8ac25a943
  - gitlab_security_policy_project_32562_bot_b9de349db2e0dd20436d3310bb021372
  - gitlab_security_policy_project_32607_bot_0732c0283ed3a82bc840a078b257554e
  - gitlab_security_policy_project_33234_bot_88b1bc516d87c4fc96ea846204c97d79
  - gitlab_security_policy_project_33247_bot_cfe295714fbfe54ea4d9319afd21f878
  - gitlab_security_policy_project_33281_bot_245fd4ea31e088fb308297cc859b8a93
  - gitlab_security_policy_project_33779_bot_0fc492b1adc30ed7b71def3c8a28c778
  - gitlab_security_policy_project_33906_bot_30b89cb4c60fcf0893dadf40ba56a78f
  - gitlab_security_policy_project_33969_bot_28435b24931b92728dd730bf3a063c36
  - gitlab_security_policy_project_34006_bot_76949481b018f69f24cc7998060abbc6
  - gitlab_security_policy_project_36840_bot_b7caceba12ad841ff15d6d2f9759ebab
  - gitlab_security_policy_project_38269_bot_f049a4efd943916a96c3a0cefe8bde52
  - gitlab_security_policy_project_38566_bot_0ccac1143935cc7d97e9b393881d4b5e
  - gitlab_security_policy_project_38911_bot_16d6bdc97c87414e20360df2ac9afc7c
  - gitlab_security_policy_project_43177_bot_566ca641bee96ff535d335a852ce9c3d
  - gitlab_security_policy_project_7_bot_7e72a89174cbe78e97d551e6f92c5d91
  - gitlab_security_policy_project_82449_bot_f67d6210e65533c4b2f7c985f1556e22
  - gitlab_security_policy_project_84181_bot_93055301c2b0187ebadced47192ea608
  - gitlab_security_policy_project_84367_bot_eab745afc6c35d17f61ef21a261cf75d
  - gitlab_security_policy_project_84422_bot_22144c24fc29c9ed7f8617a2cd8eadac
  - gitlab_security_policy_project_84536_bot_b3b1a6e0089b7f23728063cc5f574366
  - gitlab_security_policy_project_84858_bot_d78be3051ac27beb42d82fd43691073a
  - gitlab_security_policy_project_85684_bot_b91f0e09beab42063e1de8bc40c02576
  - gitlab_security_policy_project_98829_bot_56e179146d42b40e4d7bfa0fb858eeea
  - gitlab_security_policy_project_98832_bot_6941f3535660e621c60ab2ac550de20d
  - gitlab_security_policy_project_99023_bot_54ef85afd5fe6d9832139e79901c666c
  - gitlab_security_policy_project_99051_bot_1a7631e80c60e2b9780dd1d660f52476
  - gitlab_security_policy_project_99507_bot_9a47dbc01454cd562e89c8b13615cd1d
