fail2ban_jails:
  sshd: true
  postfix: false
  dovecot: false
  nginx_limit_req: true
memcached_socket: "/run/memcached/archwiki.sock"
wireguard_address: 10.0.0.22
wireguard_public_key: +HOjbJivvyeww7Mvej5IOZghZ000AAGxy1qN1eZZajo=
nginx_enable_http3: true
anubis_extra_rules:
  - mediawiki
