$ANSIBLE_VAULT;1.1;AES256
61383432353730376332666133623138393938306466376337646564343133376438316234303930
6439383634663433343064653336653438303538643965660a633363333866663766313136376265
37336130653162366261623834623839393833666262373839346131616334633763366161383664
3934383033366539630a323134336235636235393033613336336663343661366163333764626465
31373836323931626231313165333637396134613138326337336562663864663836316565306136
65333331663964393638623165396234306139316663366637663864313739633861386465623962
35366365623133323933626439643331363265393766396438353533373962613430376233666633
30306136663732613838353431313562333465383638636436353562633963633862636566393961
3630
