$ANSIBLE_VAULT;1.1;AES256
61613138323433346431316638353937656565633266343433343634383663316131656530653938
3064356563616631356162303861643763383263336535660a373664323630643734336337653730
32396535653664356439313664633539663639343439316639313436353036636435366563373331
6531383366663631360a663864353838356134393931383961393963656162353163636364663231
37343439333538613130626466303335653563336438666462376330656436613838366132613934
63386430363962303833383361376331366637306664346565653865633636333966646338303532
35636464613766373937333734653134646265646433386536363162363064356333303166626436
30343661623939353463313961623130646530346261316537353631613064346432343135386663
65626431666636303031663437633238323135333834633632306436353934326464
