$ANSIBLE_VAULT;1.1;AES256
66646236636333326636313632323233343039636537306433643665323766346331313834613863
6534303532626136353363336566363938353233326365310a666263643465353336383837636265
36386161663032336632663038353235353131393766663964633033376133303432623236636439
3665363762313137350a613765393437623630343866323162363634613234343062323438306465
65393933623931323930383464666337663539303639373830323962656164353233336533353631
30356333613166636330666236653733613164633634373134336636623936323361333537313763
653830316163383766316362643731303462
