---
archmanweb_dir: '/srv/http/archmanweb'
archmanweb_cache_dir: '{{ archmanweb_dir }}/cache'
archmanweb_domain: 'man.archlinux.org'
archmanweb_allowed_hosts: ["{{ archmanweb_domain }}"]
archmanweb_nginx_conf: '/etc/nginx/nginx.d/archmanweb.conf'
archmanweb_repository: 'https://gitlab.archlinux.org/archlinux/archmanweb.git'
#archmanweb_pgp_key: ['932BA3FA0C86812A32D1F54DAB5964AEB9FEDDDC']   # Jakub Klinkovsk√Ω (lahwaacz)
archmanweb_forced_deploy: false

archmanweb_db: 'archmanweb'
archmanweb_db_host: 'localhost'
archmanweb_db_user: 'archmanweb'
