---
archwiki_dir: '/srv/http/archwiki'
archwiki_domain: 'wiki.archlinux.org'
archwiki_nginx_conf: '/etc/nginx/nginx.d/archwiki.conf'
archwiki_user: 'archwiki'
archwiki_repository: 'https://github.com/archlinux/archwiki.git'
archwiki_version: '1.33.0-4'
archwiki_question_answer_file: '/srv/http/archwiki/registration-question-answer.txt'

archwiki_socket: '/run/php-fpm/archwiki.socket'
archwiki_memcached_socket: '/run/memcached/archwiki.sock'
archwiki_memcached_memory: 2048

archwiki_db: 'archwiki'
archwiki_db_host: 'localhost'
archwiki_db_user: 'archwiki'
