dbscripts_commit: cde46716a8cde5424297c9ed350d43ad26e8b1f1
dbscripts_update: true
dbscripts_pgp_emails: ['jelle@archlinux.org', 'anthraxx@archlinux.org']

git_state_repo: /srv/repos/state
git_pkg_cache: /srv/repos/pkg-cache
lock_dir: /srv/repos/lock

junior_developer_repos:
  - core-staging
  - core-staging-debug
  - core-testing
  - core-testing-debug

developer_repos:
  - core
  - core-debug

junior_packager_repos:
  - extra-staging
  - extra-staging-debug
  - extra-testing
  - extra-testing-debug
  - gnome-unstable
  - gnome-unstable-debug
  - kde-unstable
  - kde-unstable-debug
  - multilib-staging
  - multilib-staging-debug
  - multilib-testing
  - multilib-testing-debug

packager_repos:
  - extra
  - extra-debug
  - multilib
  - multilib-debug
