$ANSIBLE_VAULT;1.1;AES256
37333033396362326135303834396162393066363065643735633835663133633137313465333634
6432333837613936356335366431383431393961366665370a633732663763636263623461323431
37386266346438386661613139366532373663393735326262353939613239663538613063626639
3532663566303035310a303865303861303330626236333065353737316361343461383432373564
37383765376634373262393331333237363264656561383638326430626131353732343738366139
61653230366466386639626335356263623163363235633236343135623263306163326365323237
33646265386230363962366530306265633264636137623735313061663232366266663836613433
32366661616535373336633939613466316561373461353563366135383432303433623037613761
35326466363235656233633761646665383935616634663266386133353631323264303863373336
33633363636661396437623836333030326230636363353236656438316365346630633838333265
30393866643939666337306130353233336639653939663061353663323238366232613139626635
39643232613736366135633130346139613232373232323166653961623732383134346635383366
3830
