$ANSIBLE_VAULT;1.1;AES256
35373665633536326637383435336666373865663435616337393261383437623538386631373263
6466376330616466646262653066363966383361646163660a336663396139303933316332643336
65323838303737306162626630623834333138336166646561653634333838396335643765346332
3231306236323631360a663333663430633063656434323565623432656566303762323466343031
30363464323261383738336264613834306534353566336361626535323632323533383734393734
35313630383138343935616235336431626133333662326561346165663566303538333134323736
62636532393834373765323830333763313533616339346263653538626531323435386335323838
61623239643539323138643662633136643266336633373039626338633234393037626336616134
32643933373166336265383535613235643936306161666630623436393538633331
