modules:
  http_prometheus:
    prober: http
    timeout: 5s
    http:
      headers:
        User-Agent: "blackbox-monitoring"
  tls_connect:
    prober: tcp
    timeout: 5s
    tcp:
      tls: true
  smtp_starttls:
    prober: tcp
    timeout: 5s
    tcp:
      query_response:
        - expect: "^220 ([^ ]+) ESMTP (.+)$"
        - send: "EHLO prober\r"
        - expect: "^250-STARTTLS"
        - send: "STARTTLS\r"
        - expect: "^220"
        - starttls: true
        - send: "EHLO prober\r"
        - expect: "^250"
        - send: "QUIT\r"
