---
postgres_listen_addresses: 'localhost'
postgres_max_connections: '100'

postgres_ssl: 'off'
postgres_ssl_prefer_server_ciphers: 'on'
postgres_ssl_cert_file: '/var/lib/postgres/data/fullchain.pem'
postgres_ssl_key_file: '/var/lib/postgres/data/privkey.pem'
postgres_ssl_ca_file: '/var/lib/postgres/data/chain.pem'

postgres_shared_buffers: '128MB'

postgres_ssl_hosts: []
