---

- name: install dependencies
  pacman: name=docker,python-docker,python-gitlab,gitlab-runner state=present
  when: ansible_facts['os_family'] == "Arch Linux"
  notify: restart gitlab-runner

- name: install dependencies
  apt: name=docker-ce,gitlab-runner state=present update_cache=yes
  when: ansible_facts['os_family'] == "Debian"
  notify: restart gitlab-runner

- name: start docker
  systemd: name=docker enabled=yes state=started daemon_reload=yes

- name: open firewall holes
  firewalld: port={{ item }} permanent=true state=enabled immediate=yes
  when: configure_firewall
  with_items:
    - "8093/tcp"
  tags:
    - firewall

- name: make docker0 interface trusted
  firewalld: interface=docker0 zone=trusted permanent=true state=enabled immediate=yes
  when: configure_firewall
  tags:
    - firewall

- name: register gitlab-runner
  command: >
    gitlab-runner register
    --non-interactive
    --url=https://gitlab.archlinux.org/
    --docker-image=alpine:latest
    --tag-list=docker
    --registration-token="{{ vault_gitlab_runner_registration_token }}"
    --executor=docker
    --description="{{ inventory_hostname }}"
    --run-untagged=false
    --docker-tlsverify=true
    --locked=false
    --access-level=not_protected
  args:
    creates: /etc/gitlab-runner/config.toml

- name: increase concurrency
  lineinfile:
    path: /etc/gitlab-runner/config.toml
    regexp: '^concurrent = .*'
    line: concurrent = 100
  notify: restart gitlab-runner

- name: enable and start gitlab runner service
  systemd: name=gitlab-runner state=started enabled=yes daemon_reload=yes
