$ANSIBLE_VAULT;1.1;AES256
65303663303932363739396437666234643931363965336463623337313033613434343765613839
6235396365663964633536313166396166663530373233350a373233636130646566636635303139
31393531396238626536383164383461326538356166333866353261643163653864326362353963
6166376534633430660a653938393665623933643931303131363034383034353639623331653164
66666437343733386632666533323261626564366233373638323735663163323831323833393531
63373364326436363937396330363234393134636139303036303666376230303431353939636534
37383130653037326330363965386337386137323135303634633635306266626530613837316137
66323134366464376433356137353934626634366562396466323432653862633137636632363335
64306361623162313564613630663438346231613332396438343334393566303334663666386266
38336137313034336461383239646432626231633932343039323536663439633264656261313533
33663465316266343235663733636364353632386266626263616334653733353531646634383437
37626630303436383561373266323061343936366561623239306635353866643332353762653163
66323565653964326565303266326432323230383937316165313237313634393764343335316234
31363538326334313135353363666363393739643133616461316538323030376335396537613135
383362393536376139313530393234323631
