---

- name: setup gemini.archlinux.org
  hosts: gemini.archlinux.org
  remote_user: root
  vars:
    archweb_db_host: 'apollo.archlinux.org'
    dbscripts_commit: '20191022'
  roles:
    - { role: common }
    - { role: tools }
    - { role: firewalld }
    - { role: sshd }
    - { role: root_ssh }
    - { role: borg_client, tags: ['borg'] }
    - { role: sudo, tags: ['archusers'] }
    - { role: certbot }
    - { role: nginx }
    - { role: archusers }
    - { role: dbscripts, repos_domain: "repos.archlinux.org", repos_rsync_domain: "rsync.archlinux.org", svntogit_repos: "/srv/svntogit/repos", postgres_ssl: 'on', tags: ['archusers'] }
    - { role: archweb, archweb_site: false, archweb_services: true, archweb_mirrorcheck_locations: [5, 6] }
    - { role: sources, sources_domain: "sources.archlinux.org", sources_dir: "/srv/sources" }
    - { role: archive }
    - { role: postfix, postfix_relayhost: "mail.archlinux.org" }
    - { role: fail2ban }
    - sogrep
