---

- name: setup orion
  hosts: orion.archlinux.org
  remote_user: root
  roles:
    - { role: common }
    - { role: tools }
    - { role: sshd }
    - { role: root_ssh }
    - { role: borg_client, tags: ['borg'] }
    - { role: opendkim, dkim_selector: orion, tags: ['mail'] }
    - { role: dovecot }
    - { role: spampd, tags: ["mail"] }
    - { role: unbound, tags: ["mail"] }
    - { role: postfwd, tags: ['mail'] }
    - { role: postfix, postfix_server: true, postfix_smtpd_public: true, tags: ['mail'] }
    - { role: archusers }
    - { role: certbot }
    - { role: nginx }
    - sogrep
    - { role: sudo, tags: ['archusers'] }
    - { role: archweb, archweb_site: false, archweb_services: false, archweb_donor_import: true, archweb_mirrorcheck_locations: [5, 6] }
    - { role: fail2ban }
