---

- name: setup soyuz
  hosts: soyuz
  remote_user: root
  roles:
    - { role: common, tags: ['common'] }
    - { role: tools, tags: ['tools'] }
    - { role: sshd, tags: ['sshd'] }
    - { role: root_ssh, tags: ['root_ssh'] }
    - { role: borg-client, backup_host: "borg@vostok.archlinux.org", backup_dir: "/backup/soyuz", postgres_backup_dir: "/var/lib/postgres/backup", tags: ['borg'] }
    - { role: opendkim, dkim_selector: soyuz, tags: ['mail'] }
    - { role: postfix, postfix_server: false, tags: ['mail'] }
    - { role: archusers, tags: ['archusers'] }
    - { role: nginx, letsencrypt_validation_dir: "/var/lib/letsencrypt", tags: ["nginx"] }
    - { role: sudo, tags: ['sudo', 'archusers'] }
    - { role: postgres, tags: ['postgres'] }
    - { role: quassel, quassel_domain: "quassel.archlinux.org", tags: ['quassel'] }
    - { role: syncrepo, mirror_domain: "mirror.pkgbuild.com", tags: ['syncrepo', 'nginx'] }
    - { role: sogrep, tags: ['sogrep'] }
    - { role: archbuild, tags: ['archbuild'] }
    - { role: public_html, public_domain: "pkgbuild.com", tags: ['public_html', 'nginx'] }
