$ANSIBLE_VAULT;1.1;AES256
36386238396566383134383863393335643433623562663234633636623736646436393763366634
6433623161396330656136336334653061393763613933620a666334336435663931323366376335
39353761303331323739333663663635636132363161336463636466373764366365616438633031
3466383831323730350a666236643261623639383236353263383436396630383534316234633637
63333933363434666162633739623262653863643231623266313638366565306237333362336530
63343139373962633462633962366433333138643136663262316437386461353339666132383334
63386236613030653766326263656438636431326638376163303764383632353430663162633031
65333434363233653039343033356133636134356134623532343565343734653138653636396662
37666134623864643536353339313861626438383465663934383230313561306663326438316463
31353532343634666434656438336231306336323732303236386332376564653036393366303036
35633635366139636639393965383030363533663631656631626365383136623236383765666532
33636136333861653766656237306666656464383030623232393765646466313532393132313663
36616437353233373439653737393730393436626431623239626535653238613633393335376538
37303932323531393338663666653163613230343133643030363964336530346337386631646232
623031653961366666646332386431663366
