$ANSIBLE_VAULT;1.1;AES256
38383330633231666363386538363739633263646339626536353462303834636437663430323232
3464356562643131363763666233623433626432306433630a383066366539613065336237346635
35303837663861663636323665356632663330626233363561383235396234346339353230343337
6661353664343436390a646536333132396662336639653162393335313232366139623262366366
35633838613765633637633434656434376265333930333733643135623537626665613762666163
39306263633935633533316134356630633161623165343532646136623265616430636461306437
30633961613530343263313266643935386663386537393133616561653566343939333233613639
34633964373033636566316538313239653930356366353033366338396238326135376363373034
61333561616563646131623536633365666132323962643461333236373532333338613433303564
31613339383065366666373435623434633432396535313833393739623539623633663264613562
65666435383631363436633839636638646438613263383365316235623631643439303862613666
34636533366333393762
